name: github_release_apk_updater
description: "A Flutter plugin to automatically check for, download, and install updates directly from GitHub releases."
version: 1.0.6
repository: https://github.com/dozmaz/github_release_apk_updater
homepage: https://github.com/dozmaz/github_release_apk_updater

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  dio: any
  flutter:
    sdk: flutter
  package_info_plus: any
  path_provider: any
  plugin_platform_interface: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.7.0
  build_runner: ^2.15.0

flutter:
  plugin:
    platforms:
      android:
        package: blog.guidocutipa.github_release_apk_updater
        pluginClass: GithubReleaseApkUpdaterPlugin
